<?xml version="1.0"?>
<!DOCTYPE aoCars [
<!ELEMENT aoCars (car)*>
<!ELEMENT car ANY>
<!ATTLIST car id ID #REQUIRED>
<!ATTLIST car price CDATA #REQUIRED>
]>
<aoCars>
  <car id="_16798977" price="32000">This is an Acura, info set from XML!</car>
  <car id="_33570817" price="44550">This is an award winning AMX that features a nut-and-bolt restoration that utilizes many N.O.S. parts. Among the new old stock parts are rocker moldings, deck lid, rear valance, front fenders, grille, hood molding, headlight bezels, parking lights/turn signal lenses and housings, all side marker lamps, door latches and strikers, door seals, jamb bumpers, trunk seal, outer door handles with correct finish, gas tank, bolts and sending unit, along with many other components and trim details.  This is a very well-equipped example that is finished in Bayshore Blue with a black interior; among the features are tilt steering wheel, center armrest and cushion (“buddy seat”), AM/FM radio, Light Group, Visibility Group, optional 15-inch Machine wheels, tinted glass, air conditioning, front spoiler, black rally stripes, black vinyl bucket seats, Go Package, space-saver spare, dual mirrors with driver’s side remote; power steering and brakes. The engine is a 390-cid, 325-hp V-8 that is mated to a four-speed manual transmission.  This fine AMX has placed first at the Hoosier Auto Show in Indianapolis in both 2003 and 2004. A first place was also won by this AMC at a Cincinnati concours d’elegance in 2005. It has also won the First Junior Award at the AACA spring meet, and that fall, it won the AACA Senior Award at the prestigious and largely attended Hershey meet. In 2012 it won the AACA Grand National Award in Tennessee. As recently as 2013, it obtained the AACA top honor by winning the Senior Grand National Award in Moline, Illinois.   The vendor does state that the original 360-cid engine was replaced with this correct, rebuilt 390-cid version that was optional to the car in 1970. The Bayshore Blue paint is also original spec for this 1970 model; it has been applied to replace the original Glen Green.</car>
  <car id="_50331649" price="126500">The 1906 American Tourist was the first production automobile designed by Harry C. Stutz. Its Stutz-designed side-valve four-cylinder 336 cubic inch engine broke no new ground, but equally showed Stutz's appreciation for the desirable attributes of touring car engines, in this case a practical operating range of 125- to 1,450-rpm. Live axle suspension with semi-elliptical leaf springs and platform rear suspension with a semi-elliptical cross spring were characteristic of the highest quality automobiles of the day. Harry Stutz's Tourist showed its value, quality and practicality by earning its place in the American model lineup from its inception in 1906 until 1913, just a year before American ceased production in 1914. The Stutz-designed four-cylinder engine powered all automobiles built by American Motor Cars until 1913. American built some 45,000 automobiles in just 9 years, double the production of Packards in the same period. This 1906 American Tourist Roi des Belges Touring was restored years ago for one of the founders of car collecting in America, Dr. Samuel Scher. It is one of very few surviving examples of its model, a nearly unique example of an important milestone in both the evolution of the American automobile and in the development of Harry Stutz's experience and his concepts of automobile design. Finished in red with black mudguards, it has red leather upholstery and a black cloth top. The American eagle mascot spreads its wings proudly on the radiator cap. There are Rushmore acetylene headlights, Gray & Davis kerosene sidelights, a magnificent Rushmore swivel-mounted acetylene searchlight on the cowl, Stewart speedometer and a brass bulb horn. The thoroughness of its restoration and the care it's had in the last two generations are reflected in the set of side curtains that still accompany it. One of the great automobiles of early American history, it will still show its heels to traffic with style and panache that is almost unknown today.</car>
  <car id="_67124481" price="47300">It’s a car. It’s a boat. Actually, it’s both. Nothing draws a crowd like an Amphicar. Developed in West Germany, the Amphicar was aimed squarely at America’s leisure market and debuted at the 1961 New York Auto Show. As the culmination of a 15-year, $25 million development program, the Amphicar was conceived by amphibious-vehicle pioneer Hans Trippel. A curious fusion of road-going and aquatic transport, it remains particularly popular as a unique and eye-catching collector’s item with its amphibious design and twin-screw propellers. Powered by a 1,147-cc Triumph Herald inline four-cylinder engine mated to a four-speed manual transmission, it directed power to the rear wheels on land and, once on water, to twin propellers at the rear. This Amphicar is finished in Beach White and features a black soft-top, red steel wheels and chrome hubcaps, whitewall tires, red and white two-tone upholstery. Amphicar marketing highlighted the vehicle’s ease of operation, and its unofficial “770” designation referred to its factory-claimed top speeds of seven knots on water and 70-mph on land. It is generally agreed that 3,878 were built through 1967, with the majority exported to the USA, far fewer are thought to remain.</car>
  <car id="_83910657" price="52250">The Aston Martin DB7 was launched in March 1993 at the Geneva Motor Show and marked the return of the six-cylinder Aston Martin. Penned by Ian Callum, the rakish lines of the DB7 were beautiful, hearkening back to iconic models from the sixties. Although it was originally intended to be an "entry level" Aston Martin, it quickly evolved into much more.  In 1999 Aston Martin squeezed its first production 12-cylinder engine into the DB7 to create the potent DB7 Vantage. The Aston Martin DB7 is a Grand Touring car in the finest tradition. Produced from 1994 to 2004, the DB7 proved to be one of the most popular Aston Martin models.  For those seeking employment as an international spy, there is really only one marque of automobile for daily transportation needs, the heralded name of Aston Martin. This DB7 nicely fits the bill with a well-trimmed black leather interior that is fully loaded with all of the accouterment required for sports car motoring. Aside from very light wear to the driver-side seat bolster and a high-end Alpine entertainment system, this low-mile Vantage appears like new from the inside. On the Titanium Silver exterior, no obvious blemishes are to be found on the soft folding top or the paint and trim. It is fitted with 19-inch alloy rims wrapped with Yokohama rubber. The 5.9-liter, 420 horsepower V-12 and five-speed transmission with steering shift will ensure great performance on the next mission.</car>
  <car id="_100670977" price="145750">The beautiful supercharged 852 Phaeton Sedan offered here has been driven and enjoyed by its owner, an enthusiastic Auburn, Indiana resident, on several regional ACD Club tours. Reliability has been excellent, and the car runs beautifully and performs well at highway speeds, with the optional “Dual Ratio” rear axle functioning properly, as confirmed by recent road testing by an Auctions America specialist. No less beautiful cosmetically, it is in “high-end driver” condition, with excellent chrome, interior, and top, and only slight age showing to the rich green paint.   The tan leather interior is an attractive complement to the body tone and features elegant instrumentation with a damascene-type dashboard. The exterior exhaust pipes and optional sidemounted spare with cover add sportiness and style. Chrome headlights and factory installed trunk were both optional equipment in 1935. The trunk adds 13.5-cubic feet of luggage space. Wire wheels, whitewall tires, dual mirrors, chrome taillights and vacuum windshield wipers are all part of this desirable platform. It will continue to be an outstanding tour car and welcome at ACD Club events. The Auburn has been certified by the Auburn-Cord-Duesenberg Club as a Category No. 1, Certified Original Car. It is also one of the most drivable and enjoyable of all Full Classics, as recognized by the CCCA.  Introduced in 1935, the all-new 851 featured beautiful Gordon Buehrig-penned styling and offered an optional Switzer-Cummins centrifugal supercharger, which boosted output by 30 percent to 150-hp. Developed by Kurt Beier at Schwitzer-Cummins and adapted to the Auburn-Lycoming inline eight-cylinder engine by Augie Duesenberg and Pearl Watson, the supercharger ran at six times engine speed and generated useful boost from 2,000-rpm upwards.   The Auburn 852 was the last hurrah for the Auburn Automobile Company. As was the case with many of the independent manufacturers, their final products were often among their best. The styling, introduced in 1935, was the last Gordon Buehrig designed Auburn line to see production.   Established in 1903, the Auburn Automobile Company matured into a well-respected builder of reliable cars, but it was not until E.L. Cord assumed the company’s presidency in 1924 that its market stature grew. In fact, as the once-buoyant auto market collapsed following Black Tuesday, Auburn’s sales continued to increase. By 1931, Auburn was the 13th largest American automaker, but the triumph was short-lived, as sales fell drastically in 1932 and 1933.</car>
  <car id="_117464577" price="64900">In March 1995 at the Geneva Motor Show, Rolls-Royce Motors unveiled its convertible version of the Continental R, the Bentley Azure. Now considered a modern classic, the Pininfarina-designed Azure is acknowledged by Rolls-Royce and Bentley enthusiasts to be one of the most desirable cars ever built. The two-door open tourer seats four adults in sumptuous comfort, thanks in part to its brilliant computer-controlled automatic ride control. Whether enjoying a leisurely top-down Sunday drive or covering great distances at speed and experiencing the thrill of putting the car through its paces, the well-mannered Azure is the definitive driver’s car. This 2000 Azure convertible has covered only 26,000 miles from new and is beautifully presented in rich black body color; accented with matching red-piped black leather upholstery and a black cloth top. It has Bentley embroidered headrests, tinted glass, and two matching Bentley umbrellas in the trunk, as well as all the standard luxury conveniences expected of a Bentley. It is in exceptionally clean and well maintained condition consistent with the low recorded mileage. Boosted by a Garrett turbocharger the big 6.75-liter V-8 delivers 400 brake horsepower and 590-lb/ft of torque. The limited production Azure convertible was as dominant on the road as its luxury and exclusivity dominated the boulevards of resorts and spas. Priced in excess of $300,000 when new, it is an automobile to be proud to own and drive. Only 1,308 units were built until production ended in 2003. In that time, just 709 Azures were exported to the U.S. market.</car>
  <car id="_134230529" price="42900">When BMW undertook the manufacturing of Renzo Rivolta’s Isetta in 1955, the firm incorporated some changes. The drivetrain was redesigned to use their 247 cubic centimeter four-cycle motorcycle engine. The gearbox output was coupled to a shaft through a rubber universal joint, which led, through another rubber joint, to the chain case. Inside were double drive chains running in oil to the solid rear axle. This arrangement made the whole power unit much quieter and reduced vibration. In fact, so much of the car was re-engineered that no earlier Iso parts were used, nor were they interchangeable. The front suspension was also reconfigured to a swing arm arrangement. Changes to the body included raising the headlights above the fenders so that they attached directly to the body. As with this car, in 1956 the engine displacement was increased to 297 cubic centimeters and compression was raised to achieve 13 horsepower. Although top speed did not increase from 53-mph, there was a marked increase in much-welcome torque, which helped on hills. More than 161,000 Isettas were built through 1962, along with some 34,000 BMW 600s, an elongated, four-passenger version with a flat-twin engine and a conventional rear axle. This rare example of a surviving European bubble window Isetta has the highly desirable “Z mold trim” and two-tone paint. It is the recipient of an excellent restoration and is very attractive in red and white; it has primarily red tartan upholstery and a black fabric sunroof. Very well detailed with front vent windows, dual mirrors, luggage rack and whitewall tires, it is an excellent example of the popular European microcar.</car>
  <car id="_134242049" price="98450">The Z8 is BMW’s spiritual successor to the 1950s 507 roadster. Both cars use a long hood with short deck design to create a powerful and sporty appearance. This limited production roadster with optional hardtop is equipped with a 4.9-liter DOHC V-8 as used in the M5, mated to a proper six-speed manual gearbox and producing nearly 400-hp. The Z8 has electronic traction control and four-wheel ventilated disc brakes with ABS and factory alloy wheels. This example has less than 51,000 miles and is handsomely presented in Titanium Silver Metallic with a black leather interior. The removable hardtop is in the same color as the body and has a rear window defogger. The soft-top is black and the remote mirrors are chrome. Luxury appointments are also prominent; these include alloy and leather interior trim elements, air conditioning, AM/FM/CD, Xenon lighting, fixed hoop rollover protection; power seats, door locks, windows, steering and brakes.  In developing the Z8, BMW married form and function like never before. The design is flawless from any angle, inside and out, carried over from Henrik Fisker’s Z07 concept introduced at Tokyo in 1997 and paying homage to the Count Albrecht Goertz-designed 507 of the 1950s with side vents, a sleek front end and such retro touches as a banjo-type steering wheel.  With 50/50 weight distribution and the acceleration of a Ferrari 360 Modena, this was BMW’s fastest roadster to date, the movie car choice of James Bond and a true supercar with brilliant braking and cornering. Motor Trend magazine brought out its true “M” potential, achieving a 0- to 60-mph sprint of just 4.2 seconds, and top speed was reported as 155-mph.</car>
  <car id="_151005953" price="56100">In 1949, this was Buick’s glamorous way to go places – with its top up or down it was one of the sharpest cars on any boulevard. Motoring thrills are gathered by its behavior on the road, wide seating and ease of having standard equipment such as the automatically-operated top, front seat and windows. This wonderful car has been restored from top-to-bottom starting with a solid, rust-free southern car that was one family owned for 50 years. The restoration process utilized mainly N.O.S. parts. The car has received new paint, interior, top, chrome, wiring and mechanicals; including new brakes, engine rebuild, transmission rebuild – even the factory radio has been refurbished and is in perfect working condition. The Sequoia Cream finish is handsomely matched with a low-profile black soft-top that has red piping, and the interior is upholstered in red vinyl. The engine is a factory original Fireball 248-cid, 115-hp straight eight-cylinder and the transmission is automatic. Among the features found on the Buick are “VentiPorts,” AM radio, clock, backup lights, fender skirts, bumper guards with accessory bar, distinguishing brightwork, red steel wheels with factory wheel covers and wide whitewall tires. This is a quite uncommon and sought-after Buick that has an iconic status and is presented in a meticulous fashion.</car>
  <car id="_151011841" price="13200">First introduced as a personal luxury car, Buick took their Riviera, offered bigger engine displacement, and the “Gentleman’s Musclecar” was born. Over 1.1 million Riveras were produced from 1963 to 1999, and perhaps the most memorable versions were the early seventies’ boattail styles seen from 1971-1973. Seen here, this two-tone green Riviera has the big 455 cubic inch engine topped with a four-barrel carburetor. The engine compartment is loaded with goodies such as power steering and brakes, as well as air conditioning. The interior is in remarkably well-preserved condition with medium green cloth fabrics and matching door panels and dash. The odometer shows 30,462 miles; perhaps giving reason for the fine original quality throughout. It also features cruise control, power windows and power seat. This is a prime example of Buick’s successful, powerful and memorable boattail Riviera.</car>
  <car id="_151015681" price="16500">Buick’s Grand National was menacing right out of the box. Most were black, with blackout trim. The interior was finished in a plethora of gray tones and fabrics, and the instrumentation included a tach and a boost gauge. Naturally, the suspension got stiffer springs and anti-roll bars, plus Goodyear radials on special aluminum wheels. Buick continued development on the GN package, and soon came an intercooler, along with 235 horsepower for 1986, then 245 horses in ’87. This black Buick shows only 40,000 miles from new and still wears its original paint. The two-tone cloth interior is in excellent condition and features an automatic transmission, power locks and windows, air conditioning, AM/FM/cassette and tilt wheel. The 3.8 turbo V-6 engine compartment is also detailed to appear as new.</car>
  <car id="_167784961" price="73700">Named Biarritz, the 1956 Cadillac Eldorado Convertible carried a substantial factory price tag of $6,501 when new. With only 2,150 examples built, this Biarritz is truly a masterpiece of Cadillac craftsmanship. It is difficult to find a better example of GM's styling and engineering prowess than viewing the 1956 Cadillac Eldorado. Surviving examples remain highly sought-after today and they continue to rank among the most luxurious and elegant automobiles ever to come from GM during the fabulous 1950s. For the first time, the Eldorado also had a hardtop model that was named the Seville.  This Eldorado is finished in Black with a black convertible top and a classly black and white two-tone interior. It is equipped with gold-finished Saber-Spoke wheels, wide whitewall tires, radio, clock; power top, seat, windows, steering and brakes, plus all the other inherent Eldorado features for 1956. The 1956 Cadillac is powered by a twin-carb 365-cid V-8 engine with 305-hp and is connected to a Hydra-Matic automatic transmission. This power equipment was standard in period for this model.</car>
  <car id="_167785217" price="181500">In 1957 Dwight Eisenhower was in the White House, Sputnik orbited planet Earth and Elvis Presley appeared on the Ed Sullivan show for the third and what would be last time. Presley also owned a new 1957 Cadillac Eldorado Biarritz, the car that marked the pinnacle of automotive ownership for many Americans. At over $7,000, it was achievable for the individual who had attained personal success. Someone like Elvis, climbing their way up the ladder and had the desire to reward themselves with the best that money could buy. It spoke to that success with vast amounts of chrome, impressive highway-devouring performance, and styling that only Harley Earl's studio could have dreamt up.</car>
  <car id="_184561665" price="28200">Running a 350-cid V-8 engine and a turbo 350 automatic transmission, this Bel Air wagon is presented in light blue with a white roof that has been intentionally aged to show patina and give it a rat rod style. The Chevy has front and rear Air Ride Technologies suspension, dual exhaust, polished aluminum American Racing wheels, power steering and power brakes.</car>
  <car id="_184561921" price="48400">While this Chevy truck displays many original attributes, it has been refurbished by A-Car Restorations of Reedsville, Wisconsin using a 350-cid V-8 General Motors crate engine that is matched to a floor-shift five-speed manual transmission. The rear end is a nine-inch Ford unit. The truck is very nicely presented in Viper Red and has a tan interior with a black tonneau cover. The steel wheels are color-keyed and have been mounted with wide whitewalls and are fit with chrome hubcaps and trim rings. Heidts front suspension, stainless steel exhaust, stereo; power steering and brakes are other features on this fine looking 1955 3100 truck.</car>
  <car id="_184561922" price="57200">The Tri-Five years from Chevrolet have always been favored 1950s American classics. This 1955 Bel Air is shown in Skyline Blue with India Ivory and beautiful two-tone slate blue upholstery. The interior is very well-restored with great attention to fit and finish of each component. It is powered by a 265 V-8 with a three-speed manual overdrive transmission. The engine bay is highlighted with chrome valve covers and has been detailed to better than factory standards. The underside of the chassis is equally detailed and impressive. Four new Coker wide whitewall radials have been mounted onto the correct steel wheels. The car also has full wheel covers, fender skirts, dual exhaust, dual external mirrors, tinted windshield, power top, original radio and clock, plus front and rear bumper guards. This is a prime opportunity to forego the time and cost of a restoration and to simply purchase a fully restored Bel Air.</car>
  <car id="_184561923" price="101200">This custom Bel Air has received a total frame-off restoration that includes extensive new sheetmetal. The chassis is from Custom Progressive and is powder-coated in blue that matches the body color. It is powered by a fuel-injected GM LS2 6.0-liter V-8 that is dyno’d at 507 horsepower at the rear wheels. Along with a custom cam, the engine has a Magnuson supercharger with 40-pound injectors and custom intercooler with a remote custom tank. The transmission is a T-56 six-speed manual that has a hydraulic clutch system. Other mechanical workings consist of C4 Corvette front suspension components and narrowed Dana 44 rear end, also from a C4. The power brakes are hydraulic and by Hydratech with 12-inch Wilwood brake rotors and four-piston calipers. The custom radiator has custom computer-activated cooling fans. The custom exhaust system is stainless steel with stainless Flowmaster mufflers.  The interior is custom and executed in leather and suede. Lizard skin ceramic insulating material is applied to the floors and interior roof. The seats are a 2 + 2 layout with full power front seats with a center console. The polished tilt steering column is from Air Ride Technologies and has dimmer controls. Billet Specialties provided the leather wrapped custom steering wheel. The polished, one-piece dash insert is from Pete’s Fabrications and is fitted with custom Classic Instruments. The heater and air conditioning unit are by Vintage Air; power windows with power wing windows and a Pioneer stereo system complete a welcoming environment.  The exterior finish is also custom and utilizes PPG materials. Additional eye-catching details are seen in a stainless steel grille, custom polished billet hood hinges, new Danchuk body badges, custom polished stainless trim elements, Advanced chrome plating, smoothie custom-fabricated one-piece front and rear bumpers, plus Boze Speedster wheels. This is a beautifully built and presented machine that has been stored and cared for in a climate-controlled environment.</car>
  <car id="_184561924" price="74800">This 1955 Nomad is finished in black over a red interior and is driven by a LT1 V-8 engine with a 4I60 transmission. The engine has an all street performance front drive and plenty of chrome engine accents are found under the hood. There is also a polished Griffin radiator with a custom chrome front support. Rack-and-pinion steering, four-wheel disc brakes, Billet Specialties wheels, BFGoodrich tires, all new chrome and stainless that is “show-quality” polished are all great features for this car, as is the louvered hood. The interior has Classic gauges, Pete and Jakes dash trim, Iditdit steering column with a custom wood wheel, hidden Sony Xplod system that features a subwoofer six-disc changer, amp and a matching Sony head unit. The car is a breathtaking beauty and has won numerous awards and was featured in a 2013 Street Rodder magazine.</car>
  <car id="_184562177" price="148500">The debate as to which of the classic mid-fifties Chevys is the best looking will go on forever. Some prefer the subtlety of the 1955, while others thrive on the flamboyance of the finned 1957 models; many enthusiasts opine the 1956 embodies the perfect balance of the other two.  The subtle changes to the Chevy’s body design in 1956 gave it a fresh, new, lighter appearance. Inside, the dash retained the dual cowl look, but now the mesh matched that of the front grille. Chevy also proved to the world that their full-size cars were not just rolling sculptures by setting new speed records and winning races.   This lovely Matador Red and Indian Ivory example features a deluxe red and white interior, and it has received a full and complete rotisserie restoration. This outstanding Chevy runs with a V-8 engine that has dual four-barrel carbs and “batwing” air cleaner assembly. The engine was prepared by Atlanta’s Tom Trainer, a recognized authority on this type of engine.  The car is generously equipped and includes a Powerglide transmission, Wonderbar radio, Continental kit, rare NOS rear antenna, windshield washer, wire-basket factory wheel covers, whitewall tires, dual mirrors, date-coded spiral shocks, front and rear accessory bumper guards, all-stainless steel exhaust system; power top, seat, windows, brakes and steering.  This exceptional offering has always been a trailered show car that resides in a climate-controlled setting. In February 2010 it won first place in the 1956 “Trailer Restored Senior Class” at the 18th Annual Chevy Classic Winter Nationals in Cocoa Beach, Florida, impressively scoring 991 points from a possible 1,000 total score.</car>
  <car id="_184562689" price="33950">Powered by a rebuilt 350-cid V-8 engine, this beautiful Biscayne was the recipient of a frame up restoration in 2008. The interior was completely redone by Brian Bohide. The candy red paint is beautiful and set off nicely by the all new chrome, stainless steel and five-spoke wheels. All of the glass was replaced as well. With multiple best paint awards at the Duck Tail run, this outstanding example is ready for you to enjoy and show.</car>
  <car id="_184562945" price="36850">This is an award-winning Chevy Apache that is vibrant in bright orange with an equally eye-catching orange and white interior that features bucket seats. The engine has been upgraded to a 350-cid V-8 GM crate engine that is mated to an automatic transmission. Along with power steering and power brakes, the Apache displays a finished oak bed floor, dual mirrors, chrome five-spoke wheels and low-profile blackwall tires.</car>
  <car id="_184562946" price="40700">This full custom Impala looks quite sporty in its blue finish with white pearl interior. The 348-cid V-8 engine is set up with three carburetors and mated to a four-speed manual transmission. The engine compartment is presented with a great deal of chrome components, stainless hose and Aeroquip fittings. The interior has a matching white custom headliner, striped acrylic control knobs, chrome dashboard, bucket seats, center console and modern white-faced instrumentation. The Impala rides low and has a louvered hood, lake pipes, chrome reverse wheels and whitewall tires.</car>
  <car id="_184563713" price="28200">Running a 350-cid V-8 engine and a turbo 350 automatic transmission, this Bel Air wagon is presented in light blue with a white roof that has been intentionally aged to show patina and give it a rat rod style. The Chevy has front and rear Air Ride Technologies suspension, dual exhaust, polished aluminum American Racing wheels, power steering and power brakes.</car>